# Generated by Django 6.1.1 on 2026-09-10 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Discord', 'Email'", max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('value', models.CharField(help_text="e.g. '!Elias#3519' or 'elias@elias.me'", max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(help_text='Email or phone number', max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('role_title', models.CharField(help_text="e.g. 'web designer'", max_length=150)),
                ('typewriter_roles', models.CharField(help_text="Comma separated roles for the typewriter effect, e.g. 'developer, creator, gamer'", max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('is_available_for_freelance', models.BooleanField(default=True)),
                ('hero_illustration', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('about_text', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('location', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('description', models.TextField(help_text='Short summary shown on the project card')),
                ('overview', models.TextField(blank=True, help_text="Longer write-up shown in the '#overview' section of the detail page")),
                ('live_url', models.URLField(blank=True)),
                ('cached_url', models.URLField(blank=True)),
                ('role', models.CharField(blank=True, help_text="e.g. 'Solo developer'", max_length=100)),
                ('duration', models.CharField(blank=True, help_text="e.g. '~2 weeks'", max_length=100)),
                ('status', models.CharField(blank=True, help_text="e.g. 'Archived', 'Live'", max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('show_as_bars', models.BooleanField(default=False, help_text='Checked = items render as progress bars (like Languages). Unchecked = tag cloud.')),
            ],
            options={
                'verbose_name_plural': 'Skill categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NowBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(default='In progress', max_length=50)),
                ('description', models.TextField()),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('stack', models.CharField(help_text="e.g. 'HTML · CSS · JS'", max_length=150)),
                ('next_note', models.CharField(blank=True, help_text="e.g. 'Next: case study polish'", max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='now_building/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='now_building', to='main.profile')),
            ],
            options={
                'verbose_name_plural': 'Now building',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('target_value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, help_text="e.g. '+', 'yr', '%'", max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='main.profile')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon_svg', models.TextField(blank=True, help_text='Inner SVG markup only (paths/rects), no outer <svg> tag. Rendered inside a 24x24 viewBox.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('proficiency_percent', models.PositiveSmallIntegerField(default=0, help_text='Only used when the category shows bars')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.skillcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='main.tag'),
        ),
    ]
